
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borse-web-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borse-web-api
  template:
    metadata:
      labels:
        app: borse-web-api
    spec:
      containers:
        - name: borse-web-api
          image: dmrkrn/borse-web-api:latest  # Docker Hub image name
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: borse-web-api-env # (Optional: You can use K8s Secret for .env variables)
---
apiVersion: v1
kind: Service
metadata:
  name: borse-web-api-service
spec:
  selector:
    app: borse-web-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer # To expose the port externally, you can use NodePort or LoadBalancer
  # If you want to access port 4000 directly from outside, you should use type: LoadBalancer or Ingress.